[tools]
dagger = "latest"
go = "1.25"
"go:github.com/bufbuild/buf/cmd/buf" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
