name: ci
on:
    push:
        branches: [main]
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Checks
              uses: dagger/dagger-for-github@v8.3.0
              with:
                  version: v0.19.11
                  verb: check

            - name: Build client
              uses: dagger/dagger-for-github@v8.3.0
              with:
                  version: v0.19.11
                  verb: call
                  args: golang build --args ./client/ directory --path /out/ export --path ./out

            - name: Build server
              uses: dagger/dagger-for-github@v8.3.0
              with:
                  version: v0.19.11
                  verb: call
                  args: golang build --args ./server/ directory --path /out/ export --path ./out